apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.service.image }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.service.image | quote }}
      {{- if and (ne $.Values.environment "io") (contains "rc-" $.Values.service.tag) }}
      feature: stage
      {{- else if ne $.Values.environment "io" }}
      feature: {{ $.Values.service.tag | quote }}
      {{- else }}
      tag: {{ $.Values.service.tag | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ $.Values.service.image | quote }}
        {{- if and (ne $.Values.environment "io") (contains "rc-" $.Values.service.tag) }}
        feature: stage
        {{- else if ne $.Values.environment "io" }}
        feature: {{ $.Values.service.tag | quote }}
        {{- else }}
        tag: {{ $.Values.service.tag | quote }}
        {{- end }}
    spec:
      containers:
      - name: {{ $.Values.service.image }}-service
        image: ghcr.io/getsproud/{{ $.Values.service.image }}:{{ $.Values.service.tag }}
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz/readiness/{{ $.Values.service.image }}
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz/liveness/{{ $.Values.service.image }}
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: COTE_LOG
          value: "false"
        - name: DOMAIN
          value: {{ $.Values.domain }}.{{ $.Values.environment }}
        - name: NODE_ENV
          value: {{ $.Values.nodeEnv }}
        - name: COTE_DISCOVERY_REDIS_HOST
          value: {{ $.Values.redis.service }}.{{ $.Values.namespace}}.svc.cluster.local
        - name: DISCOVERY_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      imagePullSecrets:
      - name: gh-registry
---
