name: Production Deployment

on:
  push:
    branches:
    - main
    paths-ignore:
    - '*.md'
    - LICENSE

env:
  IMAGE: gateway

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses:  actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Tag
      run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: dominicrico
        password: ${{ secrets.GHP_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ghcr.io/getsproud/${{ env.IMAGE }}:${{ GIT_TAG }}, ghcr.io/getsproud/${{ env.IMAGE }}:latest
        target: production
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Deploy to Cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_STAGE }}
        KUBECTL_VERSION: "1.20"
      with:
        args: -n sproud-stage set image --record deployment/${{ env.IMAGE }}-app ${{ env.IMAGE }}-service=ghcr.io/getsproud/${{ env.IMAGE }}:${{ GIT_TAG }}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: releases-stage
        SLACK_USERNAME: sproud.bot
        SLACK_TITLE: Deployed ${{ env.IMAGE }} v${{ GIT_TAG }} service on https://sproud.io
