name: Stage Deployment

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - '*.md'
    - LICENSE

env:
  IMAGE: gateway

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses:  actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Message
      id: log
      run: echo "::set-output name=message::$(git log --no-merges --oneline ${{ github.sha }}...HEAD)"

    - name: Show Commits
      run:  echo "${{ steps.log.outputs.message }}"
